### ISSUE TITLE
Error in unexported rule: Invalid rule class hasn't been exported by a bzl file

### ISSUE THREAD

**Issue by lalten** [fmeum/with_cfg.bzl#123]
I tried to wrap with_cfg in a rule factory function but it doesn't let me:
`Error in unexported rule: Invalid rule class hasn't been exported by a bzl file`

Any ideas how that could be made to work?

Minimalistic repro:

`MODULE.bazel`
```
module(name="with_cfg_test")
bazel_dep(name = "rules_cc", version = "0.0.10")
bazel_dep(name = "with_cfg.bzl", version = "0.5.0")
```
`BUILD`
```
load("//:make_rule.bzl", "opt_cc_test")
opt_cc_test(name = "test")
```
`make_rule.bzl`
```
load("@rules_cc//cc:defs.bzl", "cc_test")
load("@with_cfg.bzl", "with_cfg")

def _make_opt_test(test_rule):
    _opt_test_builder = with_cfg(test_rule)
    _opt_test_builder.set("compilation_mode", "opt")
    opt_test, _opt_test_internal = _opt_test_builder.build()
    return opt_test

opt_cc_test = _make_opt_test(cc_test)
```
```
❯ bazel build //:test
ERROR: Traceback (most recent call last):
        File "/Users/lalten/with-cfg-test/BUILD", line 2, column 12, in <toplevel>
                opt_cc_test(name = "test")
        File "/private/var/tmp/_bazel_lalten/aa056832d6db174de01387ef980bd8ea/external/with_cfg.bzl~/with_cfg/private/wrapper.bzl", line 18, column 46, in lambda
                return lambda *, name, **kwargs: _wrapper(
        File "/private/var/tmp/_bazel_lalten/aa056832d6db174de01387ef980bd8ea/external/with_cfg.bzl~/with_cfg/private/wrapper.bzl", line 157, column 24, in _wrapper
                transitioning_alias(
Error in unexported rule: Invalid rule class hasn't been exported by a bzl file
WARNING: Target pattern parsing failed.
ERROR: Skipping '//:test': no such target '//:test': target 'test' not declared in package '' defined by /Users/lalten/with-cfg-test/BUILD
ERROR: no such target '//:test': target 'test' not declared in package '' defined by /Users/lalten/with-cfg-test/BUILD
INFO: Elapsed time: 0.051s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

**Comment by fmeum** [comment]
You need to return `_opt_test_internal` from your factory and assign it to some top-level variable. Bazel enforces that all rules are assigned to one and the first return value of the builder is necessarily a macro.

**Comment by lalten** [comment]
indeed! Thank you very much for your blazingly fast and correct response 🙇
