### ISSUE TITLE
Cannot encode CompilationMode as JSON when using reset feature

### ISSUE THREAD

**Issue by SimonaAlina** [fmeum/with_cfg.bzl#63]
The CompilationMode value can't be serialised as JSON value in the original settings.

The error is:
```
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_simona/3099fbc7895a08f739515284f34cf219/external/with_cfg.bzl~0.2.1/with_cfg/private/transition.bzl", line 21, column 56, in lambda
		return lambda settings, attr: _transition_base_impl(
	File "/private/var/tmp/_bazel_simona/3099fbc7895a08f739515284f34cf219/external/with_cfg.bzl~0.2.1/with_cfg/private/transition.bzl", line 91, column 69, in _transition_base_impl
		new_settings[str(original_settings_label)] = json.encode(settings)
Error in encode: in dict key "//command_line_option:compilation_mode": cannot encode CompilationMode as JSON
ERROR: /Users/simona/github/bazel-demos/tools/my-tool/BUILD:14:15: Errors encountered while applying Starlark transition
```

The error can be reproduced using the code from here: https://github.com/SimonaAlina/bazel-demos . More details in the readme file.

**Comment by SimonaAlina** [comment]
Thank you for your quick PR. I still want to bring a possible issue after your fix because I tried something similar locally and at some point I received the following error:
```

**Comment by SimonaAlina** [comment]
Thank you for your timely fix. I want to bring a possible issue after your PR because I tried something similar locally (stringifying the CompilationMode) and at some point I received the following error:

```
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_simona/1402bd498b8e8d0ccb9317cd43842857/external/with_cfg.bzl~override/with_cfg/private/transition.bzl", line 21, column 56, in lambda
		return lambda settings, attr: _transition_base_impl(
	File "/private/var/tmp/_bazel_simona/1402bd498b8e8d0ccb9317cd43842857/external/with_cfg.bzl~override/with_cfg/private/transition.bzl", line 84, column 21, in _transition_base_impl
		fail(
Error in fail: Cannot transition {"//command_line_option:compilation_mode": opt} to {"//command_line_option:compilation_mode": "opt"} because the original settings are not empty: {"//command_line_option:compilation_mode":"fastbuild","@@//:hz_ts_project_original_settings":""}.Using a rule produced with with_cfg in the transitive closure of another such rule with a further transition between them is currently not supported. Please file an issue at https://github.com/fmeum/with_cfg.bzl to explain your use case.
ERROR: BUILD.bazel:21:14: Errors encountered while applying Starlark transition
```

and then I had to use the same setting with values as string type here: https://github.com/fmeum/with_cfg.bzl/blob/main/with_cfg/private/transition.bzl#L74 where I replaced the `settings.items()` with the new dictionary with values as string. 

Do you think the same problem will appear after your fix?

**Comment by fmeum** [comment]
Nice catch (and thank you for the clean reproducers)!

I will submit a follow-up fix for this tomorrow and then get a release out.
